### ISSUE TITLE
Nit picks

### ISSUE THREAD

**Issue by chriscardillo** [CodeForPhilly/cfp-data-pipeline#1]
- Upgrade to gusty 0.3.1 (this will require changing `GustyDag` to `create_dag` in `dags.py`)
- Remove gusty demo dags `breakfast` and `stock_predictions`
- Change defaults in `analyses` dag (e.g. John Templeton is currently the owner)
- Update README
- Optional: you can add defaults in `create_dag` if you want, instead of using `METADATA.yml`. Like [this](https://github.com/chriscardillo/gusty-demo/blob/d9d3535e47a97746e424bf3576c5c89cf86eb47b/airflow/dags/dags.py#L22-L26)

**Comment by machow** [comment]
@chriscardillo thanks for these helpful notes! I've...

* removed the demo dags
* updated the README (at least stripped it down 😬)
* changed defaults to rename owner and email
* renamed dag from analyses to prototype

Any chance I could persuade you to make the changes to upgrade to gusty 0.3.1? :) :) :)

**Comment by chriscardillo** [comment]
No problem! PR here: https://github.com/CodeForPhilly/cfp-data-pipeline/pull/3
