### ISSUE TITLE
github tap errors due to a label having a description

### ISSUE THREAD

**Issue by machow** [CodeForPhilly/cfp-data-pipeline#14]
See https://github.com/singer-io/tap-github/issues/95

The tap currently doesn't expect descriptions to be filled out, which causes an error for labels like the one below ( "Something isn't working" is the description):

![image](https://user-images.githubusercontent.com/2574498/105780096-f9dad500-5f2c-11eb-986e-5e591391a536.png)

A PR to resolve has been open on the tap repo for a while, so it may be easier to fork & fix?

**Comment by dherbst** [comment]
I'm not seeing this error when I run this locally - are you seeing this on production?

**Comment by machow** [comment]
Yeah--on http://161.35.188.229:8080/.

```
Extraction failed (1): Errors during transform: [issue.labels.0.description: Good for newcomers does not match {'type': ['null']} 

...
```

I wonder if it's because one of the issues got a newcomer label? (Which makes sense to use as a label!)

**Comment by luandy64** [comment]
@machow @dherbst I'm working on merging a PR to fix this. [Follow along here](https://github.com/singer-io/tap-github/pull/102)

**Comment by dherbst** [comment]
Thanks @luandy64 we already fixed this in our fork.

**Comment by luandy64** [comment]
I did a quick compare and noticed your fork has `issue_events.issue.milestone` as a string. [source](https://github.com/dherbst/tap-github/blob/c124793d16d83c73027ed7ab864976a9d7df91bb/tap_github/schemas/issue_events.json#L172-L177)

Is issue milestones a feature you use? If so, does the string datatype what you see on the record?

I'm getting an object on my end:
```
'milestone': {'title': 'new-feature'}
```

**Comment by dherbst** [comment]
So far we have not used the tap on a repo that has assigned milestones to an issue, so this hasn't come up yet.  Thanks for pointing it out.

**Comment by luandy64** [comment]
Hopefully you can cherry pick this commit https://github.com/singer-io/tap-github/pull/102/commits/36e937e8e6f2bd843d61309512c80e9e52fda0fe
