### ISSUE TITLE
Remove need to duplicate environment variables

### ISSUE THREAD

**Issue by machow** [CodeForPhilly/cfp-data-pipeline#15]
Right now, getting the tap to work with @chriscardillo required setting a new env variable in `.env` called `TARGET_POSTGRES_POSTGRES_USERNAME`. However, this variable is identical to `DEFAULT_USER`. Are we able to just set the value of `TARGET_POSTGRES_POSTGRES_USERNAME` to that of `DEFAULT_USER` in the meltano config?

cc @chriscardillo @dherbst

**Comment by dherbst** [comment]
I think we can simplify this, yes.  PR #16 should resolve this.
