### ISSUE TITLE
Have taps ingest to separate schemas

### ISSUE THREAD

**Issue by machow** [CodeForPhilly/cfp-data-pipeline#27]
Right now our postgres target for the github and slack taps uses the views schema. One challenge for analysts with this is that they'll see a bunch of tables under the views schema, but without a clear way to distinguish the source.

If we dump tap onto its own schema, then analytic engineers can put nicely transformed results onto views.

![image](https://user-images.githubusercontent.com/2574498/106330691-e8e9d680-6240-11eb-9699-639eb095e15a.png)

**Comment by dherbst** [comment]
We can use plugin inheritance http://meltano.com/docs/configuration.html#multiple-plugin-configurations to configure target-postgres to a different schema per tap.  

I'll start a PR.

**Comment by dherbst** [comment]
This was merged to staging.
