### ISSUE TITLE
basic deploy to digitalocean via github actions

### ISSUE THREAD

**Issue by machow** [CodeForPhilly/cfp-data-pipeline#7]
Just for the sake of getting something data scientists / analysts can plug into, I can implement a quick deployment to digital ocean. 

This will let @chriscardillo and co. cook up something more generally useful!

Was thinking...

* secrets stored in github settings
* use github action with workflow_dispatch to trigger deployment
* option to trigger just copying the dag file in from the repo's main branch
* option to copy in the whole git repo, and nuking everything with `docker-compose down`

**Comment by machow** [comment]
cc @chriscardillo crude but effective implementation!

https://github.com/CodeForPhilly/cfp-data-pipeline/blob/master/.github/workflows/main.yml

Just ssh's into a digitalocean instance, clones repo, and restarts docker-compose.

[action output here](https://github.com/CodeForPhilly/cfp-data-pipeline/actions)

**Comment by chriscardillo** [comment]
Nice! I definitely see the rough edges.

Is it being hosted anywhere yet?
